---
abstract: 'allows RT to do authentication via a service which supports the Bitcard API'
author:
  - 'Kevin Riggle <kevinr@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-Bitcard
no_index:
  directory:
    - html
    - inc
requires:
  Authen::Bitcard: 0.86
  Encode: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
version: 0.04_01
