abstract: Allows RT to do authentication via a service which supports the Bitcard API
author: Kevin Riggle <kevinr@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.63
license: GPL version 2
name: RT-Authen-Bitcard
no_index: 
  directory: 
    - html
    - inc
    - t
requires: 
  Authen::Bitcard: 0
version: 0.01
