--- 
abstract: Allows RT to do authentication via a service which supports the Bitcard API
author: 
  - Kevin Riggle <kevinr@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: GPL2
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Authen-Bitcard
no_index: 
  directory: 
    - html
    - inc
    - t
requires: 
  Authen::Bitcard: 0.86
  Encode: 0
  perl: 5.8.3
version: 0.04
