---
abstract: 'Allows RT to do authentication via a service which supports the Bitcard API'
author:
  - 'Kevin Riggle <kevinr@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: GPL2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-Bitcard
no_index:
  directory:
    - html
    - inc
requires:
  Authen::Bitcard: 0.86
  Encode: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.04
